name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install black
        run: pip install black

      - name: Check code formatting
        run: black --check .

  run-tests:
    needs: black-format # ✅ This job runs only if black-format passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    needs: run-tests # ✅ This job runs only if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy only from main branch
    steps:
      - name: Deploy
        run: echo "Deploying the app..."
