name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pylint pytest

      - name: Run flake8
        run: |
          echo "Running flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run black (check only)
        run: |
          echo "Running black..."
          black . --check

      - name: Run pylint
        run: |
          echo "Running pylint..."
          pylint $(find . -name "*.py" ! -path "./venv/*")

      - name: Run tests with pytest
        run: |
          echo "Running pytest..."
          pytest
